baseURL = "https://RCJacH.github.io/"
title = "RCJacH"
theme = "hugo-icarus-theme"
DefaultContentLanguage = "en"

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"


[permalinks]
    post = "/blog/:filename/"


[menu]
[[menu.main]]
    identifier = "blog"
    url  = "/blog/"
    weight = 1

[[menu.main]]
    identifier = "profile"
    url  = "/profile/"
    weight = 2

[[menu.main]]
    identifier = "contact"
    url   = "/contact/"
    weight = 3

[[menu.language]]
    name = "English"
    url = "/"
    weight = 1
    Pre = "<i class='flag-icon flag-icon-ca'></i>"
[[menu.language]]
    name = "中文"
    url = "cn/"
    weight = 2
    Pre = "<i class='flag-icon flag-icon-cn'></i>"

[params]
    author = "RCJacH"
    bio = "Music Composer, Songwriter, and Producer for the casual and serious listeners."
    location = "Earth"
    site_description = ""
    copyright = "RCJacH. ALL RIGHTS RESERVED."
    avatar = "img/profile-pic.jpg"
    gravatar = ""
    logo = "img/logo.png"
    search = "//google.com/search"
    disable_mathjax = false # set to true to disable MathJax
    noReadingTime = true

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["blog"]

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    # Add custom assets with their paths relative to the static folder
    custom_css = ["css/flag.css"]
    custom_js  = ["js/contact-form.js","js/functions.js"]
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "RCJacH@outlook.com"

# Enter a link for the follow button on the left
[params.profile]
    # follow_button = "https://github.com/RCJacH"

[params.staticman]
    endpoint = "https://api.staticman.net/v2/entry/"
    username = ""
    repository = "RCJacH-hugo-source"
    branch = "master"

[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "RCJacH"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = "rcjach"
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = "rcjach"
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = ""
    weibo           = "rcjach"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = false
    categories = true
    tags = true
    tag_cloud = true

[Languages]
[Languages.en]
    weight = 0
    languageName = "English"
    languageCode = "en"
[Languages.en.Taxonomies]
    tags = "tags"
    categories = "categories"

[Languages.cn]
    weight = 1
    languageName = "中文"
    languageCode = "cn"
    bio = "Music Composer, Songwriter, and Producer for the casual and serious listeners."
    copyright = "所有版权归RCJacH拥有。"
    search = "//cn.bing.com/search"
    date_format = "2006-01-02"
    noWordCount = true
[Languages.cn.Taxonomies]
    tags = "tags"
    categories = "categories"